services:
  - type: web
    name: animated-nature-wallpapers
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
